=== pudj/iis/Zadatak1/Models/Event.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="event">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="id" type="xs:integer" />
			<xs:element name="name" type="xs:string" />
			<xs:element name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Party"/>
						<xs:enumeration value="Concert"/>
						<xs:enumeration value="Festival"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="url" type="xs:string" />
			<xs:element name="promoter" type="xs:string" />
			<xs:element name="startdate" type="xs:dateTime" />
			<xs:element name="enddate" type="xs:dateTime" />
			<xs:element name="price" type="xs:decimal" />
			<xs:element name="venue">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="id" type="xs:ID" />
						<xs:element name="name" type="xs:string" />
						<xs:element name="address" type="xs:string" />
						<xs:element name="city" type="xs:string" />
						<xs:element name="country" type="xs:string" />
						<xs:element name="postalcode" type="xs:string" />
						<xs:element name="contactname" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== pudj/iis/Zadatak1/Models/Event.xml
<?xml version="1.0" encoding="utf-8"?>
<event xsi:noNamespaceSchemaLocation="Event.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>1</id>
	<name>string</name>
	<type>Party</type>
	<url>string</url>
	<promoter>string</promoter>
	<startdate>1972-06-20T04:30:25.12</startdate>
	<enddate>1978-07-05T05:55:08.53</enddate>
	<price>-689969.765094196</price>
	<venue>
		<id>AAAAB</id>
		<name>string</name>
		<address>string</address>
		<city>string</city>
		<country>string</country>
		<postalcode>string</postalcode>
		<contactname>string</contactname>
	</venue>
</event>
